const ROUTES = {
  MAIN: 'MAIN',
  HOME: 'HOME',
  DASHBOARD: 'DASHBOARD',
  PROFILE: 'PROFILE',
  CHECK_IN: 'CHECK IN',
  REGISTER_IDENTITY: 'REGISTER IDENTITY',
  SETTINGS: 'SETTINGS',
  TEST: 'TEST',
};

export default ROUTES;
