const ROUTES = {
  MAIN: 'MAIN',
  HOME: 'HOME',
  CALENDAR: 'CALENDAR',
  PROFILE: 'PROFILE',
  CAMERA: 'CAMERA',
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD: 'FORGOT PASSWORD',
  TUTORIALS: 'TUTORIALS',
  VIEW_ALL_AGENDA: 'VIEW ALL AGENDA',
  TEST: 'TEST',
};

export default ROUTES;
