const ROUTES = {
  MAIN: 'MAIN',
  HOME: 'HOME',
  CALENDAR: 'CALENDAR',
  PROFILE: 'PROFILE',
  CAMERA: 'CAMERA',
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  TEST: 'TEST',
};

export default ROUTES;
